use async_trait::async_trait;

use crate::charts::{escape_html, ChartRenderer};
use crate::error::ReportResult;
use crate::formatters::ReportFormatter;
use crate::types::{GeneratedReport, ReportFormat, ReportFinding, ReportInput, ReportKind, Severity};

pub struct HtmlFormatter;

#[async_trait]
impl ReportFormatter for HtmlFormatter {
    fn format(&self) -> ReportFormat {
        ReportFormat::Html
    }

    async fn render(&self, kind: ReportKind, input: &ReportInput) -> ReportResult<GeneratedReport> {
        let html = render_html(kind, input);
        Ok(GeneratedReport {
            kind,
            format: ReportFormat::Html,
            filename: format!("promptlab-{}-{}.html", kind.as_str(), input.scan_id),
            bytes: html.into_bytes(),
            content_type: ReportFormat::Html.content_type().into(),
        })
    }
}

fn render_html(kind: ReportKind, input: &ReportInput) -> String {
    let severity_chart = ChartRenderer::severity_bar_svg(&input.charts, 420, 180);
    let category_chart = ChartRenderer::category_bar_svg(&input.charts, 420, 160);
    let risk_gauge = ChartRenderer::risk_gauge_svg(
        input.charts.risk_score,
        input.charts.total_findings.max(1),
        200,
        120,
    );

    let findings_html = render_findings(kind, &input.findings);
    let recommendations_html = render_recommendations(&input.recommendations);
    let compliance_section = if kind == ReportKind::Compliance {
        render_compliance(&input.findings)
    } else {
        String::new()
    };

    let executive_summary = render_executive_summary(kind, input);

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>{title} — {project}</title>
<style>
:root {{ --bg:#0f172a; --card:#1e293b; --text:#f1f5f9; --muted:#94a3b8; --accent:#6366f1; }}
* {{ box-sizing:border-box; margin:0; padding:0; }}
body {{ font-family: system-ui, -apple-system, sans-serif; background:var(--bg); color:var(--text); line-height:1.6; padding:2rem; }}
.container {{ max-width:960px; margin:0 auto; }}
header {{ border-bottom:1px solid #334155; padding-bottom:1.5rem; margin-bottom:2rem; }}
h1 {{ font-size:1.75rem; margin-bottom:0.25rem; }}
.meta {{ color:var(--muted); font-size:0.875rem; }}
.badge {{ display:inline-block; padding:0.2rem 0.6rem; border-radius:999px; font-size:0.75rem; font-weight:600; text-transform:uppercase; }}
.grid {{ display:grid; grid-template-columns:repeat(auto-fit, minmax(280px, 1fr)); gap:1.5rem; margin-bottom:2rem; }}
.card {{ background:var(--card); border-radius:12px; padding:1.25rem; border:1px solid #334155; }}
.card h2 {{ font-size:1rem; margin-bottom:1rem; color:var(--muted); text-transform:uppercase; letter-spacing:0.05em; }}
.summary {{ font-size:1.05rem; margin-bottom:2rem; }}
.finding {{ border-left:4px solid; padding:1rem; margin-bottom:1rem; background:#0f172a; border-radius:0 8px 8px 0; }}
.finding h3 {{ font-size:1rem; margin-bottom:0.5rem; }}
.finding .cat {{ color:var(--muted); font-size:0.8rem; }}
.finding pre {{ background:#020617; padding:0.75rem; border-radius:6px; overflow-x:auto; white-space:pre-wrap; word-break:break-word; font-size:0.8rem; margin-top:0.35rem; }}
.kv {{ margin-top:0.6rem; }}
.kv .k {{ display:block; color:var(--muted); font-size:0.7rem; text-transform:uppercase; letter-spacing:0.05em; }}
.conf {{ color:#a5b4fc; font-weight:600; }}
.rec {{ padding:0.75rem 0; border-bottom:1px solid #334155; }}
.rec:last-child {{ border:none; }}
.sev-critical {{ border-color:#ef4444; }} .sev-high {{ border-color:#f97316; }}
.sev-medium {{ border-color:#eab308; }} .sev-low {{ border-color:#22c55e; }} .sev-info {{ border-color:#64748b; }}
.compliance {{ font-size:0.85rem; color:var(--muted); margin-top:0.25rem; }}
footer {{ margin-top:3rem; color:var(--muted); font-size:0.75rem; text-align:center; }}
</style>
</head>
<body>
<div class="container">
<header>
  <h1>{title}</h1>
  <p class="meta">{project} · Scan {scan_id} · {generated}</p>
  {target_line}
</header>

<section class="summary">{executive_summary}</section>

<div class="grid">
  <div class="card"><h2>Risk Score</h2>{risk_gauge}</div>
  <div class="card"><h2>Severity Distribution</h2>{severity_chart}</div>
  <div class="card"><h2>Category Breakdown</h2>{category_chart}</div>
</div>

<section class="card" style="margin-bottom:2rem">
  <h2>Findings ({finding_count})</h2>
  {findings_html}
</section>

<section class="card" style="margin-bottom:2rem">
  <h2>Recommendations</h2>
  {recommendations_html}
</section>

{compliance_section}

<footer>Generated by PromptLab · {generated} · Report type: {kind}</footer>
</div>
</body>
</html>"#,
        title = kind.title(),
        project = escape_html(&input.project_name),
        scan_id = escape_html(&input.scan_id),
        generated = escape_html(&input.generated_at.to_string()),
        target_line = input
            .target_name
            .as_ref()
            .map(|t| format!(r#"<p class="meta">Target: {}</p>"#, escape_html(t)))
            .unwrap_or_default(),
        executive_summary = executive_summary,
        risk_gauge = risk_gauge,
        severity_chart = severity_chart,
        category_chart = category_chart,
        finding_count = input.findings.len(),
        findings_html = findings_html,
        recommendations_html = recommendations_html,
        compliance_section = compliance_section,
        kind = kind.as_str(),
    )
}

fn render_executive_summary(kind: ReportKind, input: &ReportInput) -> String {
    let critical = input
        .findings
        .iter()
        .filter(|f| f.severity == Severity::Critical)
        .count();
    let high = input
        .findings
        .iter()
        .filter(|f| f.severity == Severity::High)
        .count();

    match kind {
        ReportKind::Executive => format!(
            "<p><strong>{} findings</strong> identified across the AI attack surface. \
             {} critical and {} high severity issues require immediate leadership attention. \
             Risk score: {}.</p>",
            input.charts.total_findings, critical, high, input.charts.risk_score
        ),
        ReportKind::Technical => format!(
            "<p>Technical assessment of <strong>{}</strong> covering {} findings \
             with full evidence and remediation guidance.</p>",
            escape_html(&input.project_name),
            input.charts.total_findings
        ),
        ReportKind::Compliance => format!(
            "<p>Compliance mapping for <strong>{}</strong>: {} findings mapped to \
             OWASP LLM Top 10 and NIST AI RMF controls. {} require priority remediation.</p>",
            escape_html(&input.project_name),
            input.charts.total_findings,
            critical + high
        ),
    }
}

fn render_findings(kind: ReportKind, findings: &[ReportFinding]) -> String {
    if findings.is_empty() {
        return "<p>No findings recorded for this scan.</p>".into();
    }

    let detailed = kind != ReportKind::Executive;

    findings
        .iter()
        .map(|f| {
            let sev_class = format!("sev-{}", f.severity.as_str());

            let confidence = f
                .confidence
                .map(|c| format!(r#" · <span class="conf">confidence {:.0}%</span>"#, c * 100.0))
                .unwrap_or_default();

            let id_line = format!(
                r#"<p class="cat">ID: {}</p>"#,
                escape_html(&f.id)
            );

            let kv = |label: &str, value: &str| {
                format!(
                    r#"<div class="kv"><span class="k">{}</span><pre>{}</pre></div>"#,
                    escape_html(label),
                    escape_html(value)
                )
            };

            let mut details = String::new();
            if detailed {
                if let Some(req) = f.http_request.as_ref() {
                    details.push_str(&kv(
                        "HTTP request",
                        &crate::evidence::format_http_request(req),
                    ));
                }
                if let Some(resp) = f.http_response.as_ref() {
                    details.push_str(&kv(
                        "HTTP response",
                        &crate::evidence::format_http_response(resp),
                    ));
                }
                if let Some(p) = f.payload.as_ref() {
                    details.push_str(&kv("Payload sent", p));
                }
                if let Some(r) = f.response.as_ref() {
                    details.push_str(&kv("Target response", r));
                }
                if let Some(e) = f.evidence.as_ref() {
                    details.push_str(&kv("Evidence", e));
                }
            }

            let rec = f
                .recommendation
                .as_ref()
                .map(|r| format!("<p><strong>Fix:</strong> {}</p>", escape_html(r)))
                .unwrap_or_default();

            let compliance = if !f.compliance_refs.is_empty() {
                format!(
                    r#"<p class="compliance">Compliance: {}</p>"#,
                    escape_html(&f.compliance_refs.join(", "))
                )
            } else {
                String::new()
            };

            format!(
                r#"<article class="finding {sev_class}">
  <span class="badge" style="background:{color}22;color:{color}">{severity}</span>
  <h3>{title}</h3>
  {id_line}
  <p class="cat">{category} · {status}{confidence}</p>
  <p>{desc}</p>
  {details}{rec}{compliance}
</article>"#,
                sev_class = sev_class,
                color = f.severity.color(),
                severity = f.severity.as_str(),
                title = escape_html(&f.title),
                id_line = id_line,
                category = escape_html(&f.category),
                status = escape_html(&f.status),
                confidence = confidence,
                desc = escape_html(&f.description),
                details = details,
                rec = rec,
                compliance = compliance,
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn render_recommendations(recs: &[crate::types::Recommendation]) -> String {
    if recs.is_empty() {
        return "<p>No recommendations.</p>".into();
    }
    recs.iter()
        .map(|r| {
            format!(
                r#"<div class="rec">
  <span class="badge" style="background:{c}22;color:{c}">{p}</span>
  <strong>{title}</strong>
  <p>{desc}</p>
</div>"#,
                c = r.priority.color(),
                p = r.priority.as_str(),
                title = escape_html(&r.title),
                desc = escape_html(&r.description),
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn render_compliance(findings: &[ReportFinding]) -> String {
    let items: String = findings
        .iter()
        .flat_map(|f| {
            f.compliance_refs.iter().map(|r| {
                format!(
                    "<li><strong>{}</strong> — {} ({})</li>",
                    escape_html(r),
                    escape_html(&f.title),
                    f.severity.as_str()
                )
            })
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"<section class="card"><h2>Compliance Mapping</h2><ul>{items}</ul></section>"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::data::ReportDataBuilder;
    use crate::types::{ReportFinding, Severity};

    #[tokio::test]
    async fn html_contains_charts_and_findings() {
        let input = ReportDataBuilder::build(
            "s1",
            "Proj",
            None,
            vec![ReportFinding {
                id: "f1".into(),
                title: "Test".into(),
                severity: Severity::Medium,
                category: "jailbreak".into(),
                description: "desc".into(),
                payload: Some("ignore previous instructions".into()),
                response: Some("Sure, here is the answer...".into()),
                http_request: None,
                http_response: None,
                confidence: Some(0.83),
                evidence: None,
                recommendation: None,
                compliance_refs: vec!["LLM01".into()],
                status: "open".into(),
            }],
        );
        // Technical report includes payload + response + confidence per finding.
        let out = HtmlFormatter
            .render(ReportKind::Technical, &input)
            .await
            .unwrap();
        let html = String::from_utf8(out.bytes).unwrap();
        assert!(html.contains("<svg"));
        assert!(html.contains("Findings"));
        assert!(html.contains("Recommendations"));
        assert!(html.contains("Payload sent"));
        assert!(html.contains("ignore previous instructions"));
        assert!(html.contains("Target response"));
        assert!(html.contains("confidence 83%"));
        assert!(html.contains("ID: f1"));
        assert!(html.contains("Compliance: LLM01"));

        // Executive report omits raw payload/response detail.
        let exec = HtmlFormatter
            .render(ReportKind::Executive, &input)
            .await
            .unwrap();
        let exec_html = String::from_utf8(exec.bytes).unwrap();
        assert!(!exec_html.contains("Payload sent"));
    }

    #[tokio::test]
    async fn technical_html_shows_evidence_alongside_payload() {
        let input = ReportDataBuilder::build(
            "s1",
            "Proj",
            None,
            vec![ReportFinding {
                id: "f2".into(),
                title: "Leak".into(),
                severity: Severity::High,
                category: "prompt_injection".into(),
                description: "desc".into(),
                payload: Some("p".into()),
                response: Some("r".into()),
                http_request: None,
                http_response: None,
                confidence: Some(1.0),
                evidence: Some(r#"{"indicators":["UNRESTRICTED_OK"]}"#.into()),
                recommendation: Some("Add guardrails".into()),
                compliance_refs: vec![],
                status: "open".into(),
            }],
        );
        let html = String::from_utf8(
            HtmlFormatter
                .render(ReportKind::Technical, &input)
                .await
                .unwrap()
                .bytes,
        )
        .unwrap();
        assert!(html.contains("Evidence"));
        assert!(html.contains("UNRESTRICTED_OK"));
        assert!(html.contains("Fix:"));
    }
}
