import { useEffect, useRef, useState } from "react";

import { Badge } from "@/shared/components";
import { IconAi } from "@/shared/components/Icons";
import {
  generateScanRecommendations,
  type AttackRecommendationDto,
} from "@/shared/ipc/scanRecommendations";

function recommendationPriorityVariant(
  priority: string,
): "danger" | "warning" | "info" | "muted" {
  if (priority === "critical" || priority === "high") return "danger";
  if (priority === "medium") return "warning";
  if (priority === "low") return "info";
  return "muted";
}

type ScanRecommendationsPanelProps = {
  scanId: string;
  attackCategories?: string[];
  /** When false, skip loading (e.g. non-attack / draft scans). */
  enabled?: boolean;
  className?: string;
  titleAs?: "h2" | "h4";
};

export function ScanRecommendationsPanel({
  scanId,
  attackCategories = [],
  enabled = true,
  className,
  titleAs = "h2",
}: ScanRecommendationsPanelProps) {
  const [recommendations, setRecommendations] = useState<AttackRecommendationDto[]>([]);
  const [overview, setOverview] = useState<string | null>(null);
  const [source, setSource] = useState<"ai" | "fallback" | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const fetchedRef = useRef<string | null>(null);

  useEffect(() => {
    if (!enabled || !scanId) return;
    if (fetchedRef.current === scanId) return;
    fetchedRef.current = scanId;

    let cancelled = false;
    setLoading(true);
    setError(null);

    void generateScanRecommendations(scanId, attackCategories)
      .then((response) => {
        if (cancelled) return;
        setRecommendations(response.recommendations);
        setOverview(response.overview?.trim() || null);
        setSource(response.source);
      })
      .catch((err) => {
        if (cancelled) return;
        fetchedRef.current = null;
        setRecommendations([]);
        setOverview(null);
        setSource(null);
        setError(err instanceof Error ? err.message : "Failed to load recommendations");
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [scanId, enabled, attackCategories.join("|")]);

  if (!enabled) return null;

  const TitleTag = titleAs;
  const empty = recommendations.length === 0 && !overview;
  const titleClass =
    titleAs === "h2"
      ? "detail-section__title wizard-results__recommendations-title"
      : "wizard-results__recommendations-title";

  return (
    <div className={["wizard-results__recommendations", className].filter(Boolean).join(" ")}>
      <div className="wizard-results__recommendations-header">
        <TitleTag className={titleClass}>
          <IconAi className="wizard-results__recommendations-icon" aria-hidden />
          <span>Recommendations</span>
        </TitleTag>
      </div>

      {loading && empty ? (
        <p className="text-muted text-sm">Generating AI recommendations from findings…</p>
      ) : error ? (
        <p className="text-danger text-sm">{error}</p>
      ) : empty ? (
        <p className="text-muted text-sm">No recommendations available yet.</p>
      ) : (
        <>
          {overview ? (
            <p className="wizard-results__recommendations-overview">{overview}</p>
          ) : null}
          {source === "ai" ? (
            <p className="wizard-results__recommendations-meta text-muted text-sm">
              Generated by AI Runtime from scan findings.
            </p>
          ) : (
            <p className="wizard-results__recommendations-meta text-muted text-sm">
              Rule-based guidance (AI Runtime unavailable).
            </p>
          )}
          <ul className="wizard-results__recommendation-list">
            {recommendations.map((item) => (
              <li
                key={`${item.title}-${item.priority}`}
                className="wizard-results__recommendation-item"
              >
                <div className="wizard-results__recommendation-row">
                  <Badge variant={recommendationPriorityVariant(item.priority)}>
                    {item.priority}
                  </Badge>
                  <span className="wizard-results__recommendation-name">{item.title}</span>
                </div>
                <p className="wizard-results__recommendation-description text-sm">
                  {item.description}
                </p>
              </li>
            ))}
          </ul>
        </>
      )}
    </div>
  );
}
