import { IconAi } from "@/shared/components/Icons";

type YazgBadgeProps = {
  className?: string;
  /** Default: "Generated by Yazg" */
  label?: string;
};

/** Accent badge for surfaces where Yazg (AI Runtime) produced the result. */
export function YazgBadge({
  className,
  label = "Generated by Yazg",
}: YazgBadgeProps) {
  return (
    <span className={["yazg-badge", className].filter(Boolean).join(" ")}>
      <IconAi className="yazg-badge__icon" aria-hidden />
      <span className="yazg-badge__label">{label}</span>
    </span>
  );
}
