import { IconAi } from "@/shared/components/Icons";

type YazgBadgeProps = {
  className?: string;
  /** Default: "Generated by Yazg" */
  label?: string;
  /** Soft opacity/scale pulse on the whole badge while a Re-* run is active. */
  pulsing?: boolean;
};

/** Accent badge for surfaces where Yazg (AI Runtime) produced the result. */
export function YazgBadge({
  className,
  label = "Generated by Yazg",
  pulsing = false,
}: YazgBadgeProps) {
  return (
    <span
      className={["yazg-badge", pulsing ? "yazg-badge--pulsing" : "", className]
        .filter(Boolean)
        .join(" ")}
      aria-busy={pulsing || undefined}
    >
      <IconAi className="yazg-badge__icon" aria-hidden />
      <span className="yazg-badge__label">{label}</span>
    </span>
  );
}
