#!/usr/bin/env node
/** Sample report plugin — Markdown executive summary. */

import readline from 'node:readline';

function writeMessage(payload) {
  process.stdout.write(`${JSON.stringify(payload)}\n`);
}

function renderReport(params) {
  const project = params.project_name || 'Unknown Project';
  const findings = params.findings || [];
  const bySeverity = {};

  for (const f of findings) {
    const sev = (f.severity || 'info').toLowerCase();
    bySeverity[sev] = (bySeverity[sev] || 0) + 1;
  }

  const lines = [
    `# PromptLab Executive Summary — ${project}`,
    '',
    `**Total findings:** ${findings.length}`,
    '',
    '## Severity Breakdown',
    ...Object.entries(bySeverity).map(([k, v]) => `- ${k}: ${v}`),
    '',
    '## Top Findings',
    ...findings.slice(0, 5).map((f) => `- **${f.title}** (${f.severity})`),
    '',
    '_Generated by PromptLab report plugin_',
  ];

  return {
    format: 'markdown',
    content: lines.join('\n'),
    finding_count: findings.length,
  };
}

async function main() {
  const rl = readline.createInterface({ input: process.stdin });
  for await (const line of rl) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    const msg = JSON.parse(trimmed);
    if (msg.type === 'shutdown') break;

    const { id, method, params = {} } = msg;
    if (method === 'render_report' && id) {
      writeMessage({ id, result: renderReport(params) });
    }
    rl.close();
    break;
  }
}

main();
