use crate::rules::{RuleMatcher, SignalKind, StackRule};
use crate::types::{AgentFramework, AiComponent, FingerprintMethod};

pub fn framework_rules() -> Vec<StackRule> {
    vec![
        // LangChain / LangServe
        StackRule::framework(
            "langchain.path.invoke",
            AgentFramework::LangChain,
            SignalKind::UrlPath,
            0.35,
            FingerprintMethod::KnownRoutes,
            RuleMatcher::PathRegex(r"(?i)/invoke/?$"),
            "LangChain/LangServe /invoke route",
        ),
        StackRule::framework(
            "langchain.body.agent",
            AgentFramework::LangChain,
            SignalKind::ResponseBody,
            0.40,
            FingerprintMethod::Responses,
            RuleMatcher::BodyContains("langchain"),
            "LangChain referenced in response",
        ),
        StackRule::framework(
            "langchain.js.bundle",
            AgentFramework::LangChain,
            SignalKind::ResponseBody,
            0.35,
            FingerprintMethod::JavaScript,
            RuleMatcher::BodyContains("@langchain/core"),
            "LangChain JS bundle reference",
        ),
        StackRule::framework(
            "langserve.path.batch",
            AgentFramework::LangServe,
            SignalKind::UrlPath,
            0.40,
            FingerprintMethod::KnownRoutes,
            RuleMatcher::PathRegex(r"(?i)/batch/?$"),
            "LangServe /batch route",
        ),
        StackRule::framework(
            "langserve.path.playground",
            AgentFramework::LangServe,
            SignalKind::UrlPath,
            0.35,
            FingerprintMethod::KnownRoutes,
            RuleMatcher::PathRegex(r"(?i)/playground/?$"),
            "LangServe playground route",
        ),
        // LangGraph
        StackRule::framework(
            "langgraph.path.threads",
            AgentFramework::LangGraph,
            SignalKind::UrlPath,
            0.40,
            FingerprintMethod::KnownRoutes,
            RuleMatcher::PathRegex(r"(?i)/threads/"),
            "LangGraph threads API route",
        ),
        StackRule::framework(
            "langgraph.body.checkpoint",
            AgentFramework::LangGraph,
            SignalKind::ResponseBody,
            0.35,
            FingerprintMethod::Responses,
            RuleMatcher::BodyContains("langgraph"),
            "LangGraph referenced in response",
        ),
        // OpenWebUI
        StackRule::framework(
            "openwebui.path.api",
            AgentFramework::OpenWebUi,
            SignalKind::UrlPath,
            0.40,
            FingerprintMethod::KnownRoutes,
            RuleMatcher::PathRegex(r"(?i)/api/v1/chats"),
            "OpenWebUI chats API",
        ),
        StackRule::framework(
            "openwebui.body.title",
            AgentFramework::OpenWebUi,
            SignalKind::ResponseBody,
            0.35,
            FingerprintMethod::Responses,
            RuleMatcher::BodyContains("Open WebUI"),
            "OpenWebUI branding in response",
        ),
        StackRule::framework(
            "openwebui.js",
            AgentFramework::OpenWebUi,
            SignalKind::ResponseBody,
            0.30,
            FingerprintMethod::JavaScript,
            RuleMatcher::BodyContains("open-webui"),
            "OpenWebUI asset reference",
        ),
        // AnythingLLM
        StackRule::framework(
            "anythingllm.path.api",
            AgentFramework::AnythingLlm,
            SignalKind::UrlPath,
            0.40,
            FingerprintMethod::KnownRoutes,
            RuleMatcher::PathRegex(r"(?i)/api/v1/workspace"),
            "AnythingLLM workspace API",
        ),
        StackRule::framework(
            "anythingllm.body",
            AgentFramework::AnythingLlm,
            SignalKind::ResponseBody,
            0.35,
            FingerprintMethod::Responses,
            RuleMatcher::BodyContains("AnythingLLM"),
            "AnythingLLM branding",
        ),
        // Flowise
        StackRule::framework(
            "flowise.path.api",
            AgentFramework::Flowise,
            SignalKind::UrlPath,
            0.40,
            FingerprintMethod::KnownRoutes,
            RuleMatcher::PathRegex(r"(?i)/api/v1/prediction"),
            "Flowise prediction API",
        ),
        StackRule::framework(
            "flowise.body",
            AgentFramework::Flowise,
            SignalKind::ResponseBody,
            0.35,
            FingerprintMethod::Responses,
            RuleMatcher::BodyContains("Flowise"),
            "Flowise branding",
        ),
        // Dify
        StackRule::framework(
            "dify.path.api",
            AgentFramework::Dify,
            SignalKind::UrlPath,
            0.40,
            FingerprintMethod::KnownRoutes,
            RuleMatcher::PathRegex(r"(?i)/v1/chat-messages"),
            "Dify chat-messages API",
        ),
        StackRule::framework(
            "dify.body",
            AgentFramework::Dify,
            SignalKind::ResponseBody,
            0.35,
            FingerprintMethod::Responses,
            RuleMatcher::BodyContains("dify"),
            "Dify referenced in response",
        ),
        // CrewAI
        StackRule::framework(
            "crewai.body",
            AgentFramework::CrewAi,
            SignalKind::ResponseBody,
            0.40,
            FingerprintMethod::Responses,
            RuleMatcher::BodyContains("crewai"),
            "CrewAI referenced in response",
        ),
        StackRule::framework(
            "crewai.path.crew",
            AgentFramework::CrewAi,
            SignalKind::UrlPath,
            0.35,
            FingerprintMethod::KnownRoutes,
            RuleMatcher::PathRegex(r"(?i)/crew/"),
            "CrewAI crew route",
        ),
        // AutoGen
        StackRule::framework(
            "autogen.body",
            AgentFramework::AutoGen,
            SignalKind::ResponseBody,
            0.40,
            FingerprintMethod::Responses,
            RuleMatcher::BodyContains("autogen"),
            "AutoGen referenced in response",
        ),
        StackRule::framework(
            "autogen.path.agent",
            AgentFramework::AutoGen,
            SignalKind::UrlPath,
            0.35,
            FingerprintMethod::KnownRoutes,
            RuleMatcher::PathRegex(r"(?i)/agent/chat"),
            "AutoGen agent chat route",
        ),
    ]
}

pub fn component_rules() -> Vec<StackRule> {
    vec![
        // MCP Server
        StackRule::component(
            "mcp.path.sse",
            AiComponent::McpServer,
            SignalKind::UrlPath,
            0.40,
            FingerprintMethod::KnownRoutes,
            RuleMatcher::PathRegex(r"(?i)/mcp(/|$)"),
            "MCP server route",
        ),
        StackRule::component(
            "mcp.body.tools",
            AiComponent::McpServer,
            SignalKind::ResponseBody,
            0.45,
            FingerprintMethod::Responses,
            RuleMatcher::BodyJsonField {
                pointer: "/result/tools",
                equals: None,
            },
            "MCP tools/list JSON-RPC result",
        ),
        StackRule::component(
            "mcp.body.jsonrpc",
            AiComponent::McpServer,
            SignalKind::ResponseBody,
            0.35,
            FingerprintMethod::Responses,
            RuleMatcher::BodyContains("tools/list"),
            "MCP tools/list method reference",
        ),
        StackRule::component(
            "mcp.header",
            AiComponent::McpServer,
            SignalKind::Header,
            0.30,
            FingerprintMethod::Headers,
            RuleMatcher::HeaderContains {
                name: "content-type",
                value: "text/event-stream",
            },
            "MCP SSE content type",
        ),
        // RAG
        StackRule::component(
            "rag.path.retrieval",
            AiComponent::RagPipeline,
            SignalKind::UrlPath,
            0.35,
            FingerprintMethod::KnownRoutes,
            RuleMatcher::PathRegex(r"(?i)/(retrieve|retrieval|vector|embeddings/query)"),
            "RAG retrieval route",
        ),
        StackRule::component(
            "rag.body.chunks",
            AiComponent::RagPipeline,
            SignalKind::ResponseBody,
            0.40,
            FingerprintMethod::Responses,
            RuleMatcher::BodyContains("source_documents"),
            "LangChain RAG source_documents field",
        ),
        StackRule::component(
            "rag.body.context",
            AiComponent::RagPipeline,
            SignalKind::ResponseBody,
            0.35,
            FingerprintMethod::Responses,
            RuleMatcher::BodyContains("retrieved_context"),
            "Retrieved context in response",
        ),
        StackRule::component(
            "rag.openapi",
            AiComponent::RagPipeline,
            SignalKind::ResponseBody,
            0.30,
            FingerprintMethod::OpenApi,
            RuleMatcher::BodyContains("knowledge-base"),
            "Knowledge base reference",
        ),
        // Tool orchestration
        StackRule::component(
            "tools.body.function",
            AiComponent::ToolOrchestration,
            SignalKind::ResponseBody,
            0.35,
            FingerprintMethod::Responses,
            RuleMatcher::BodyJsonField {
                pointer: "/tools",
                equals: None,
            },
            "Tools array in API response",
        ),
        StackRule::component(
            "tools.path",
            AiComponent::ToolOrchestration,
            SignalKind::UrlPath,
            0.30,
            FingerprintMethod::KnownRoutes,
            RuleMatcher::PathRegex(r"(?i)/tools(/|$)"),
            "Tools API route",
        ),
    ]
}
